// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40URtenTFym6xtM0OShgo_PQhsLGO_Sk',
    appId: '1:751288510190:web:b585b92800d89d7180f5ff',
    messagingSenderId: '751288510190',
    projectId: 'todo-clone-d838e',
    authDomain: 'todo-clone-d838e.firebaseapp.com',
    storageBucket: 'todo-clone-d838e.appspot.com',
    measurementId: 'G-G862364ENV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiR8OQOYiQe_NFDRaeMbkBlxFkL7gt67E',
    appId: '1:751288510190:android:bd3bde6900464fb780f5ff',
    messagingSenderId: '751288510190',
    projectId: 'todo-clone-d838e',
    storageBucket: 'todo-clone-d838e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZVST42QTFzJN9Jp0eY6cWZUrnF5IIN0',
    appId: '1:751288510190:ios:cb3c2b0d34e03bca80f5ff',
    messagingSenderId: '751288510190',
    projectId: 'todo-clone-d838e',
    storageBucket: 'todo-clone-d838e.appspot.com',
    iosClientId: '751288510190-d8opfsbkoi42vnngc3umbi0nd1213mqf.apps.googleusercontent.com',
    iosBundleId: 'com.todo.app',
  );
}
